# This section provides information about the source, such as name and contact
# information.
# 
Source:
  name: National Whale and Dolphin Sightings and Strandings Database
  url: 
    - http://gcmd.nasa.gov/KeywordSearch/Metadata.do?Portal=amd_au&KeywordPath=&NumericId=22124&MetadataView=Full&MetadataType=0&lbnode=mdlb2
    - http://data.gbif.org/datasets/resource/79/
  email: metadata at aad.gov.au

# This section provides information about all collections provided by the 
# source.
# 
Collections:
  
# This section contains information about a single collection.
# 

# Required directory name of the collection.
# 
- Collection: DB_Cetaceans_NSSD.csv
   
  Fields:

    # Required MoL DBF fields 
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Required:
      areaid: 1
      polygonid: 1
      identifier: 
        - "Catalogue No"
      bibliographiccitation: "National Whale and Dolphin Sightings and Strandings Database, published by the Australian Antarctic Data Centre, Australia, made available under the Creative Commons Attribution 3.0 unported license. Accessed through the GBIF data portal, http://data.gbif.org/datasets/resource/79"
      collectionid: 
        - "Collection Code"
      contact: "Dave John Watts <dave.watts at aad.gov.au>"
      creator: "Australian Antarctic Data Centre, Australia"
      type: "pointoccurrence"
      dateSubmitted: "2011-11-27"
      rights: "Creative CommonsÂ® Attribution 3.0 Unported license. http://creativecommons.org/licenses/by/3.0/"
      # scientificname: "=Scientific name"
      scientificName: 
        - "Scientific name (interpreted)"
      title: "National Whale and Dolphin Sightings and Strandings Database"
      verbatimsrs: "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +units=m +no_defs"

    # Optional MoL DBF fields
    # http://www.google.com/fusiontables/DataSource?dsrcid=1348212
    #
    Optional:
      Subject: "Cetaceans"
      AreaName: 
        - "Region"
      nameAccordingTo: 
        - "Identifier"
      SurveyStartDate: 
        - "Date collected"
      SurveyEndDate: 
        - "Date collected"
      Publisher: 
        - "Data publisher"
      # Altitude?
